Task/repo
ppapou/rest-api pull request #2
Opened 2023-09-05 01:50 UTC by ppapou

2023-09-05 16:28 UTC, oleksandr-ilin requested changes
Could you pleas do some improvements?

BTW
I'm understand that naming and the architecture is dictated by the task. However I would encourage you to read this article to understand [why this approach can be considered as poorly designed](https://octoperf.com/blog/2016/10/27/impl-classes-are-evil/#why-impl-is-bad)

2023-09-05 16:28 UTC, oleksandr-ilin commented on api/build.gradle
> +sourceCompatibility = '17'
Please move all common things into the root build.gradle

2023-09-05 16:28 UTC, oleksandr-ilin commented on api/src/main/java/com/example/eventservice/EventService.java
> +public interface EventService {
That does not look like `interface` consider to change it to abstract class or even concrete class.
In general you can see this architecture does not look good.

2023-09-05 16:28 UTC, oleksandr-ilin commented on dto/src/main/java/com/example/eventservice/Event.java
> +@Setter
Consider to replace bunch of annotations and code below with one single annotation `@Data`
Furthermore. Always prefer to use `@Value` annotation first making immutable data structures and proceed with `@Data` if you have really good reasons for that.

2023-09-05 16:28 UTC, oleksandr-ilin commented on dto/src/main/java/com/example/eventservice/Event.java
> +    @Column(name = "id", nullable = false)
Guess it is redundant

2023-09-05 16:28 UTC, oleksandr-ilin commented on dto/src/main/java/com/example/eventservice/Event.java
> +    @PrePersist
Check the documentation. From top of my head there might be better way to do it using some field annotation.

2023-09-05 16:28 UTC, oleksandr-ilin commented on dto/src/main/java/com/example/eventservice/Event.java
> +    public String getTitle() {return title;}
explicit getters and setters are redundant since you are using Lombok

2023-09-05 16:28 UTC, oleksandr-ilin commented on dto/src/main/java/com/example/eventservice/Event.java
> +    public final boolean equals(Object o) {
`@Data` will do it for you. In rare cases you will need just slightly customize it with other annotations.

2023-09-05 16:28 UTC, oleksandr-ilin commented on eventapp/build.gradle
> +	id 'org.springframework.boot' version '3.1.3'
That should be defined at root build.gradle but be disabled.
Here you just need to apply the spring boot plugin.

Keep all version in one single place like `gradle.properties` and just reference it everywhere using variables.
That will help to avoid the problems when you missed to update the version somewhere and version conflict comes up.

2023-09-05 16:28 UTC, oleksandr-ilin commented on impl/build.gradle
> +    enabled = false
Why you disable it?
Since that is generic library you should not apply spring boot plugin here at all!

2023-09-05 16:28 UTC, oleksandr-ilin commented on impl/build.gradle
> +    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
It is not a good place to use spring boot starters in the library.
They contains auto configuration and that should appease at the final app configuring it. The purpose of the library is some functional piece and it usually should not configure something.
So consider to move all config beans up to the app level.

2023-09-05 21:26 UTC, ppapou commented on dto/src/main/java/com/example/eventservice/Event.java
> +    @PrePersist
According to the doc, this is the better way to set the date format

2023-09-05 22:17 UTC, ppapou commented on eventapp/build.gradle
> +	id 'org.springframework.boot' version '3.1.3'
I put only common part, just in training purpose

2023-09-08 01:00 UTC, oleksandr-ilin approved these changes
looks good

2023-09-11 23:59 UTC, oilin-clgx approved these changes
looks good

2023-09-12 00:00 UTC, merged